import React, { useState, useEffect, useCallback } from 'react';
import { connect } from 'react-redux';
import SelectCampaignPage from '../pages/SelectCampaignPage';
import { getCampaign, addCampaign } from '../../../actions/campaignActions';
import { updateSocials } from '../../../actions/formInfoActions';

const SelectCampaignContainer = ({ getCampaign, addCampaign, campaigns, updateSocials }) => {
  const [campaignData, setCampaignData] = useState([]);
  const [templateData, setTemplateData] = useState([]);
  const [defaultData, setDefaultData] = useState({
    campaign_name: '',
    company_logo_file: null,
    company_logo_url: '',
    google_search_ad: 'True',
    google_display_ad: 'True',
    facebook_feed_ad: 'True',
    facebook_display_ad: 'True',
    instagram_ad: 'True',
    ga_keyword_plan: '',
    ga_location_plan: '',
    fb_interest_plan: '',
    fb_location_plan: '',
    geotargeting: '',
    street_address: '',
    city_name: '',
    state_code: '',
    zip_code: '',
    google_account_id: '',
    facebook_account_id: '',
    facebook_page_id: '',
    objective: '',
    google_search_budget: '',
    google_display_budget: '',
    google_cpc: '',
    instagram_budget: '',
    facebook_feed_budget: '',
    facebook_audience_budget: '',
    cta: '',
    cta2: '',
    headline: '',
    headline2: '',
    ad_description: '',
    ad_link: '',
    ad_group_name: '',
    ga_campaign_length: '',
    fb_campaign_length: '',
    file_url: '',
    file_upload: null,
    fb_feed_img: null,
    instagram_img: null,
    fb_audience_img: null,
    ga_display_img: null,
    ga_square_display_img: null,
    img_option: '',
    logo_option: '',
  });

  const sampleTemplateData = [
    {
      campaign_name: 'Mascara Sale',
      google_search_ad: 'True',
      google_display_ad: 'True',
      facebook_feed_ad: 'True',
      facebook_display_ad: 'True',
      instagram_ad: 'True',
      objective: 'Generate sales or signups',
      google_search_budget: '5.00',
      google_display_budget: '5.00',
      google_cpc: '1.00',
      instagram_budget: '5.00',
      facebook_feed_budget: '5.00',
      facebook_audience_budget: '5.00',
      cta: 'Shop Now',
      cta2: 'Learn More',
      headline: 'Long Lashes in One Click!',
      headline2: 'Buy One Get One Free',
      ad_description: "Maria’s Mascara will have your lashes looking so long that they'll be doing double takes when checking your ID.",
      ga_campaign_length: '7',
      fb_campaign_length: '7',
      file_url: '',
      file_upload: null,
      fb_feed_img: null,
      instagram_img: null,
      fb_audience_img: null,
      ga_display_img: null,
      ga_square_display_img: null,
      img_option: 'custom',
      logo_option: 'custom',
    },
    {
      campaign_name: 'Men’s Sunglasses',
      google_search_ad: 'True',
      google_display_ad: 'True',
      facebook_feed_ad: 'True',
      facebook_display_ad: 'True',
      instagram_ad: 'True',
      objective: 'Increase customers visiting at my business’s physical location',
      google_search_budget: '5.00',
      google_display_budget: '5.00',
      google_cpc: '1.00',
      instagram_budget: '5.00',
      facebook_feed_budget: '5.00',
      facebook_audience_budget: '5.00',
      cta: 'Learn More',
      cta2: 'Contact Us',
      headline: 'Come SEE Why We Rock',
      headline2: 'A Pair for Every Mood',
      ad_description: 'At Miller’s Sunglasses, our quality lenses will have everyone staring at you through their own shades.',
      ga_campaign_length: '7',
      fb_campaign_length: '7',
      file_url: '',
      file_upload: null,
      fb_feed_img: null,
      instagram_img: null,
      fb_audience_img: null,
      ga_display_img: null,
      ga_square_display_img: null,
      img_option: 'custom',
      logo_option: 'custom',
    },
    {
      campaign_name: 'Bank Opening',
      google_search_ad: 'True',
      google_display_ad: 'True',
      facebook_feed_ad: 'True',
      facebook_display_ad: 'True',
      instagram_ad: 'True',
      objective: 'Increase customers visiting at my business’s physical location',
      google_search_budget: '5.00',
      google_display_budget: '5.00',
      google_cpc: '1.00',
      instagram_budget: '5.00',
      facebook_feed_budget: '5.00',
      facebook_audience_budget: '5.00',
      cta: 'Learn More',
      cta2: 'Contact Us',
      headline: 'Trusted by Millions',
      headline2: 'Since 1931',
      ad_description: 'John Smith Bank is opening a new location on Broadway! Come by and let us serve you.',
      ga_campaign_length: '7',
      fb_campaign_length: '7',
      file_url: '',
      file_upload: null,
      fb_feed_img: null,
      instagram_img: null,
      fb_audience_img: null,
      ga_display_img: null,
      ga_square_display_img: null,
      img_option: 'custom',
      logo_option: 'custom',
    },
    {
      campaign_name: 'Gym Campaign',
      google_search_ad: 'True',
      google_display_ad: 'True',
      facebook_feed_ad: 'True',
      facebook_display_ad: 'True',
      instagram_ad: 'True',
      objective: 'Generate sales or signups',
      google_search_budget: '5.00',
      google_display_budget: '5.00',
      google_cpc: '1.00',
      instagram_budget: '5.00',
      facebook_feed_budget: '5.00',
      facebook_audience_budget: '5.00',
      cta: 'Sign Up',
      cta2: 'Contact Us',
      headline: 'Gain Courage Lose Weight',
      headline2: 'With Over 100 Gym Plans',
      ad_description: "Jim's Gym has helped thousands of people meet their physical goals. Come by today and get your first month FREE.",
      ga_campaign_length: '7',
      fb_campaign_length: '7',
      file_url: '',
      file_upload: null,
      fb_feed_img: null,
      instagram_img: null,
      fb_audience_img: null,
      ga_display_img: null,
      ga_square_display_img: null,
      img_option: 'custom',
      logo_option: 'custom',
    },
    {
      campaign_name: 'Health Blog Subscription',
      google_search_ad: 'True',
      google_display_ad: 'True',
      facebook_feed_ad: 'True',
      facebook_display_ad: 'True',
      instagram_ad: 'True',
      objective: 'Generate web traffic',
      google_search_budget: '5.00',
      google_display_budget: '5.00',
      google_cpc: '1.00',
      instagram_budget: '5.00',
      facebook_feed_budget: '5.00',
      facebook_audience_budget: '5.00',
      cta: 'Subscribe',
      cta2: 'Learn More',
      headline: "Life's a Box of Berries",
      headline2: 'Healthy if You Choose So',
      ad_description: 'Health Today Magazine has everything you need to know about health, fitness, and nutrition. Subscribe for FREE today!',
      ga_campaign_length: '7',
      fb_campaign_length: '7',
      file_url: '',
      file_upload: null,
      fb_feed_img: null,
      instagram_img: null,
      fb_audience_img: null,
      ga_display_img: null,
      ga_square_display_img: null,
      img_option: 'custom',
      logo_option: 'custom',
    },
    {
      campaign_name: 'Finance App Launch',
      google_search_ad: 'True',
      google_display_ad: 'True',
      facebook_feed_ad: 'True',
      facebook_display_ad: 'True',
      instagram_ad: 'True',
      objective: 'Generate sales or signups',
      google_search_budget: '5.00',
      google_display_budget: '5.00',
      google_cpc: '1.00',
      instagram_budget: '5.00',
      facebook_feed_budget: '5.00',
      facebook_audience_budget: '5.00',
      cta: 'Learn More',
      cta2: 'Sign Up',
      headline: 'Grab Your $ by the Reigns',
      headline2: 'And Make it Rain!',
      ad_description: "SaveMore App is officially launching! We're offering a $5 sign-up credit and a $50 referral bonus!",
      ga_campaign_length: '7',
      fb_campaign_length: '7',
      file_url: '',
      file_upload: null,
      fb_feed_img: null,
      instagram_img: null,
      fb_audience_img: null,
      ga_display_img: null,
      ga_square_display_img: null,
      img_option: 'custom',
      logo_option: 'custom',
    },
    {
      campaign_name: 'Dog Treats',
      google_search_ad: 'True',
      google_display_ad: 'True',
      facebook_feed_ad: 'True',
      facebook_display_ad: 'True',
      instagram_ad: 'True',
      objective: 'Make people aware of my business',
      google_search_budget: '5.00',
      google_display_budget: '5.00',
      google_cpc: '1.00',
      instagram_budget: '5.00',
      facebook_feed_budget: '5.00',
      facebook_audience_budget: '5.00',
      cta: 'Get Offer',
      cta2: 'Shop Now',
      headline: 'Your Dog Would Click This',
      headline2: "So Why Won't You?",
      ad_description: 'Good Boy Co. is offering a 24-hour SUPER SALE on all treats throughout our website!',
      ga_campaign_length: '7',
      fb_campaign_length: '7',
      file_url: '',
      file_upload: null,
      fb_feed_img: null,
      instagram_img: null,
      fb_audience_img: null,
      ga_display_img: null,
      ga_square_display_img: null,
      img_option: 'custom',
      logo_option: 'custom',
    },
    {
      campaign_name: 'Real Estate Agent',
      google_search_ad: 'True',
      google_display_ad: 'True',
      facebook_feed_ad: 'True',
      facebook_display_ad: 'True',
      instagram_ad: 'True',
      objective: 'Make people aware of my business',
      google_search_budget: '5.00',
      google_display_budget: '5.00',
      google_cpc: '1.00',
      instagram_budget: '5.00',
      facebook_feed_budget: '5.00',
      facebook_audience_budget: '5.00',
      cta: 'Book Now',
      cta2: 'Learn More',
      headline: 'Dream Home to Real Home',
      headline2: 'Sandra Will Help!',
      ad_description: 'Sandra Williams has helped hundreds of people turn their dream home into a reality. Avoid the nightmare of doing it yourself!',
      ga_campaign_length: '7',
      fb_campaign_length: '7',
      file_url: '',
      file_upload: null,
      fb_feed_img: null,
      instagram_img: null,
      fb_audience_img: null,
      ga_display_img: null,
      ga_square_display_img: null,
      img_option: 'custom',
      logo_option: 'custom',
    },
    {
      campaign_name: 'Slice of Heaven Restaurant',
      google_search_ad: 'True',
      google_display_ad: 'True',
      facebook_feed_ad: 'True',
      facebook_display_ad: 'True',
      instagram_ad: 'True',
      objective: 'Increase customers visiting at my business’s physical location',
      google_search_budget: '5.00',
      google_display_budget: '5.00',
      google_cpc: '1.00',
      instagram_budget: '5.00',
      facebook_feed_budget: '5.00',
      facebook_audience_budget: '5.00',
      cta: 'Get Offer',
      cta2: 'See Menu',
      headline: 'Wondering Where to Eat?',
      headline2: 'Come to Slice of Heaven!',
      ad_description: "Check out Slice of Heaven's mouth watering menu and get 15% OFF your first visit! Located in Jamestown.",
      ga_campaign_length: '7',
      fb_campaign_length: '7',
      file_url: '',
      file_upload: null,
      fb_feed_img: null,
      instagram_img: null,
      fb_audience_img: null,
      ga_display_img: null,
      ga_square_display_img: null,
      img_option: 'custom',
      logo_option: 'custom',
    },
    {
      campaign_name: 'Romero Hotel',
      google_search_ad: 'True',
      google_display_ad: 'True',
      facebook_feed_ad: 'True',
      facebook_display_ad: 'True',
      instagram_ad: 'True',
      objective: 'Generate web traffic',
      google_search_budget: '5.00',
      google_display_budget: '5.00',
      google_cpc: '1.00',
      instagram_budget: '5.00',
      facebook_feed_budget: '5.00',
      facebook_audience_budget: '5.00',
      cta: 'Get Offer',
      cta2: 'Contact Us',
      headline: 'This is One Click Away',
      headline2: 'Get 25% off Your Booking',
      ad_description: "Romero Hotel is home to the most breathtaking view in Block Island! Visit our website to book the vacation that you deserve.",
      ga_campaign_length: '7',
      fb_campaign_length: '7',
      file_url: '',
      file_upload: null,
      fb_feed_img: null,
      instagram_img: null,
      fb_audience_img: null,
      ga_display_img: null,
      ga_square_display_img: null,
      img_option: 'custom',
      logo_option: 'custom',
    },
  ];

  const getCampaignData = useCallback(async () => await getCampaign());

  useEffect(() => {
    getCampaignData();
    setTemplateData(sampleTemplateData);
  }, []);

  useEffect(() => {
    setCampaignData(campaigns);
  }, [campaigns]);

  const selectDraft = (id) => {
    // Make selected campaign current
  };

  const createNewCampaign = async () => {
    const formData = new FormData();
    formData.append('draft', 'True');

    // Save Targeting options to Campaign_Info
    await addCampaign(formData);
  };

  return (
    <SelectCampaignPage
      campaigns={campaignData}
      templates={templateData}
      createNewCampaign={createNewCampaign}
      selectDraft={selectDraft}
      addCampaign={addCampaign}
      updateSocials={updateSocials}
    />
  );
};

const mapStateToProps = (state) => ({
  campaigns: state.campaigns.campaigns,
});

export default connect(mapStateToProps, {
  getCampaign,
  addCampaign,
  updateSocials,
})(SelectCampaignContainer);
