// Ad Actions
export const GET_ADS = 'GET_ADS';
export const CLEAR_ADS = 'CLEAR_ADS';
export const SAVE_AD = 'SAVE_AD';
export const POST_AD = 'POST_AD';
export const UPDATE_AD = 'UPDATE_AD';
export const DELETE_AD = 'DELETE_AD';
export const SET_LOADING = 'SET_LOADING';
export const ADS_ERROR = 'ADS_ERROR';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
// Facebook Interest Actions
export const SET_INTERESTS = 'SET_INTERESTS';
export const GET_INTERESTS = 'GET_INTERESTS';
export const UPDATE_INTERESTS = 'UPDATE_INTERESTS';
export const SAVE_INTEREST = 'SAVE_INTEREST';
export const DELETE_INTEREST = 'DELETE_INTEREST';
export const CLEAR_INTERESTS = 'CLEAR_INTERESTS';
export const UPDATE_INTEREST = 'UPDATE_INTEREST';
export const SET_INTEREST_LOADING = 'SET_INTEREST_LOADING';
export const INTERESTS_ERROR = 'LOCATIONS_ERROR';
export const RESET_FACEBOOK_INTEREST_STATE = 'RESET_FACEBOOK_INTEREST_STATE';
// Facebook Location Actions
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const UPDATE_LOCATIONS = 'UPDATE_LOCATIONS';
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';
export const SAVE_LOCATION = 'SAVE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const SET_LOCATION_LOADING = 'SET_LOCATION_LOADING';
export const LOCATIONS_ERROR = 'LOCATIONS_ERROR';
export const RESET_FACEBOOK_LOCATION_STATE = 'RESET_FACEBOOK_LOCATION_STATE';

// Google Interest Actions
export const SET_GOOGLE_INTERESTS = 'SET_GOOGLE_INTERESTS';
export const GET_GOOGLE_INTERESTS = 'GET_GOOGLE_INTERESTS';
export const SAVE_GOOGLE_INTEREST = 'SAVE_GOOGLE_INTEREST';
export const DELETE_GOOGLE_INTEREST = 'DELETE_GOOGLE_INTEREST';
export const CLEAR_GOOGLE_INTERESTS = 'CLEAR_GOOGLE_INTERESTS';
export const UPDATE_GOOGLE_INTEREST = 'UPDATE_GOOGLE_INTEREST';
export const SET_GOOGLE_INTEREST_LOADING = 'SET_GOOGLE_INTEREST_LOADING';
// Google Keyword Actions
export const SET_GOOGLE_KEYWORDS = 'SET_GOOGLE_KEYWORDS';
export const ADD_KEYWORD_TO_PLAN = 'ADD_KEYWORD_TO_PLAN';
export const CLEAR_KEYWORD_PLAN = 'CLEAR_KEYWORD_PLAN';
export const DELETE_KEYWORD_FROM_PLAN = 'DELETE_KEYWORD_FROM_PLAN';
export const GET_GOOGLE_KEYWORDS = 'GET_GOOGLE_KEYWORDS';
export const SAVE_GOOGLE_KEYWORD = 'SAVE_GOOGLE_KEYWORD';
export const DELETE_GOOGLE_KEYWORD = 'DELETE_GOOGLE_KEYWORD';
export const CLEAR_GOOGLE_KEYWORDS = 'CLEAR_GOOGLE_KEYWORDS';
export const UPDATE_GOOGLE_KEYWORD = 'UPDATE_GOOGLE_KEYWORD';
export const SET_GOOGLE_KEYWORD_LOADING = 'SET_GOOGLE_KEYWORD_LOADING';
export const UPDATE_GOOGLE_KEYWORD_ERROR = 'GOOGLE_KEYWORD_ERROR';
export const RESET_GOOGLE_KEYWORD_STATE = 'RESET_GOOGLE_KEYWORD_STATE';

// Google Location Actions
export const GET_GOOGLE_LOCATION_PLAN = 'GET_GOOGLE_LOCATION_PLAN';
export const UPDATE_GOOGLE_LOCATION_PLAN = 'GET_GOOGLE_LOCATION_PLAN';
export const DELETE_GOOGLE_LOCATION_PLAN = 'DELETE_GOOGLE_LOCATION_PLAN';
export const SAVE_GOOGLE_LOCATION_PLAN = 'SAVE_GOOGLE_LOCATION_PLAN';
export const GET_GOOGLE_LOCATIONS = 'GET_GOOGLE_LOCATIONS';
export const SET_GOOGLE_LOCATIONS = 'SET_GOOGLE_LOCATIONS';
export const CLEAR_GOOGLE_LOCATIONS = 'CLEAR_GOOGLE_LOCATIONS';
export const SAVE_GOOGLE_LOCATION = 'SAVE_GOOGLE_LOCATION';
export const UPDATE_GOOGLE_LOCATION = 'UPDATE_GOOGLE_LOCATION';
export const DELETE_GOOGLE_LOCATION = 'DELETE_GOOGLE_LOCATION';
export const SET_GOOGLE_LOCATION_LOADING = 'SET_GOOGLE_LOCATION_LOADING';
export const UPDATE_GOOGLE_LOCATIONS_ERROR = 'GOOGLE_LOCATIONS_ERROR';
export const RESET_GOOGLE_LOCATIONS_STATE = 'RESET_GOOGLE_LOCATIONS_STATE';

// Facebook Ad Accounts Actions
export const SET_FB_AD_ACCOUNTS = 'SET_FB_AD_ACCOUNTS';
export const GET_FB_AD_ACCOUNTS = 'GET_FB_AD_ACCOUNTS';
export const SAVE_FB_AD_ACCOUNT = 'SAVE_FB_AD_ACCOUNT';
export const DELETE_FB_AD_ACCOUNT = 'DELETE_FB_AD_ACCOUNT';
export const SET_FB_AD_ACCOUNT_LOADING = 'SET_FB_AD_ACCOUNT_LOADING';
export const SAVE_FB_TOKEN = 'SAVE_FB_TOKEN';
// Facebook Ad Accounts Actions
export const SET_FB_PAGES = 'SET_FB_PAGES';
export const GET_FB_PAGES = 'GET_FB_PAGES';
export const SAVE_FB_PAGE = 'SAVE_FB_PAGE';
export const DELETE_FB_PAGE = 'DELETE_FB_PAGE';
export const SET_FB_PAGE_LOADING = 'SET_FB_PAGE_LOADING';
// Google Ad Accounts Actions
export const SET_GOOGLE_AD_ACCOUNTS = 'SET_GOOGLE_AD_ACCOUNTS';
export const GET_GOOGLE_AD_ACCOUNTS = 'GET_GOOGLE_AD_ACCOUNTS';
export const SAVE_GOOGLE_AD_ACCOUNT = 'SAVE_GOOGLE_AD_ACCOUNT';
export const DELETE_GOOGLE_AD_ACCOUNT = 'DELETE_GOOGLE_AD_ACCOUNT';
export const SET_GOOGLE_AD_ACCOUNT_LOADING = 'SET_GOOGLE_AD_ACCOUNT_LOADING';
export const SAVE_GOOGLE_TOKEN = 'SAVE_GOOGLE_TOKEN';

// Google Ad Accounts Actions
export const GET_SOCIAL_AUTHS = 'GET_SOCIAL_AUTHS';

// Google Manager Accounts Actions
export const GET_GOOGLE_MANAGER_ACCOUNTS = 'GET_GOOGLE_MANAGER_ACCOUNTS';
export const SAVE_GOOGLE_MANAGER_ACCOUNT = 'SAVE_GOOGLE_MANAGER_ACCOUNT';
export const DELETE_GOOGLE_MANAGER_ACCOUNT = 'DELETE_GOOGLE_MANAGER_ACCOUNT';
export const SET_GOOGLE_MANAGER_ACCOUNT_LOADING = 'SET_GOOGLE_MANAGER_ACCOUNT_LOADING';
// Facebook Auth
export const FBPROFILE_LOADING = 'USER_LOADING';
export const FBPROFILE_LOADED = 'USER_LOADED';
export const FBAUTH_ERROR = 'AUTH_ERROR';
export const FBLOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const FBLOGIN_FAIL = 'LOGIN_FAIL';
export const FBLOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
// End Facebook Auth Actions
// Google Auth
export const GSPROFILE_LOADING = 'USER_LOADING';
export const GSPROFILE_LOADED = 'USER_LOADED';
export const GSAUTH_ERROR = 'AUTH_ERROR';
export const GSLOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GSLOGIN_FAIL = 'LOGIN_FAIL';
export const GSLOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
// End Google Auth Actions

export const UPDATE_SOCIALS = 'UPDATE_SOCIALS';
export const UPDATE_TARGETS = 'UPDATE_TARGETS';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
// Basic Info Actions
export const UPDATE_BASIC_INFO_NAME = 'UPDATE_BASIC_INFO_NAME';
export const UPDATE_BASIC_INFO_BUSINESS = 'UPDATE_BASIC_INFO_BUSINESS';
export const UPDATE_BASIC_INFO_WEBSITE = 'UPDATE_BASIC_INFO_WEBSITE';
export const UPDATE_BASIC_INFO_STREET = 'UPDATE_BASIC_INFO_STREET';
export const UPDATE_BASIC_INFO_APARTMENT = 'UPDATE_BASIC_INFO_APARTMENT';
export const UPDATE_BASIC_INFO_CITY = 'UPDATE_BASIC_INFO_CITY';
export const UPDATE_BASIC_INFO_STATE = 'UPDATE_BASIC_INFO_STATE';
export const UPDATE_BASIC_INFO_ZIP = 'UPDATE_BASIC_INFO_ZIP';
// Address Actions
export const SET_ADDRESSES = 'SET_ADDRESSES';
export const GET_ADDRESSES = 'GET_ADDRESSES';
export const SAVE_ADDRESS = 'SAVE_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const CLEAR_ADDRESSES = 'CLEAR_ADDRESSES';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const SET_ADDRESS_LOADING = 'SET_ADDRESS_LOADING';
// campaign actions
export const MAKE_CURRENT = 'MAKE_CURRENT';
export const GET_CAMPAIGNS = 'GET_CAMPAIGNS';
export const SAVE_CAMPAIGN = 'SAVE_CAMPAIGN';
export const ADD_CAMPAIGN = 'ADD_CAMPAIGN';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
export const SET_CAMPAIGN_LOADING = 'SET_CAMPAIGN_LOADING';
// campaign actions
export const GET_USER = 'GET_USER';
export const SAVE_USER = 'SAVE_USER';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const SET_USER_LOADING = 'SET_USER_LOADING';
// Conversion Actions
export const GET_GA_CONVERSIONS = 'GET_GA_CONVERSIONS';
export const SAVE_GA_CONVERSION = 'SAVE_GA_CONVERSION';
export const DELETE_GA_CONVERSION = 'DELETE_GA_CONVERSION';
export const UPDATE_GA_CONVERSION = 'UPDATE_GA_CONVERSION';
export const SET_GA_CONVERSION_LOADING = 'SET_GA_CONVERSION_LOADING';
// Pixel Actions
export const GET_FB_PIXELS = 'GET_FB_PIXELS';
export const SAVE_FB_PIXEL = 'SAVE_FB_PIXEL';
export const DELETE_FB_PIXEL = 'DELETE_FB_PIXEL';
export const UPDATE_FB_PIXEL = 'UPDATE_FB_PIXEL';
export const SET_FB_PIXEL_LOADING = 'SET_FB_PIXEL_LOADING';
// Business Info
export const GET_BUSINESS_INFOS = 'GET_BUSINESS_INFOS';
export const SAVE_BUSINESS_INFO = 'SAVE_BUSINESS_INFO';
export const ADD_BUSINESS_INFO = 'ADD_BUSINESS_INFO';
export const DELETE_BUSINESS_INFO = 'DELETE_BUSINESS_INFO';
export const UPDATE_BUSINESS_INFO = 'UPDATE_BUSINESS_INFO';
export const SET_BUSINESS_INFO_LOADING = 'SET_BUSINESS_INFO_LOADING';

// Social Account Info Actions
export const UPDATE_FACEBOOK_ACCOUNT_INFO = 'UPDATE_FACEBOOK_ACCOUNT_INFO';
export const UPDATE_GOOGLE_ACCOUNT_INFO = 'UPDATE_GOOGLE_ACCOUNT_INFO';

export const GET_GOOGLE_AD_SENSE_DATA_SUCCESS = 'GET_GOOGLE_AD_SENSE_DATA_SUCCESS';
export const GET_GOOGLE_AD_SENSE_DATA_ERROR = 'GET_GOOGLE_AD_SENSE_DATA_ERROR';
export const GET_GOOGLE_AD_SENSE_DATA_LOADING = 'GET_GOOGLE_AD_SENSE_DATA_LOADING';

export const SET_TOKEN = 'SET_TOKEN';
// export const DELETE_TOKEN = "DELETE_TOKEN";

export const GET_USER_PROFILE_INFORMATION_SUCCESS = 'GET_USER_PROFILE_INFORMATION_SUCCESS';
export const GET_USER_PROFILE_INFORMATION_LOADING = 'GET_USER_PROFILE_INFORMATION_LOADING';
export const GET_USER_PROFILE_INFORMATION_ERROR = 'GET_USER_PROFILE_INFORMATION_ERROR';

export const CREATE_GOOGLE_BUSINESS_ACCOUNT_SUCCESS = 'CREATE_GOOGLE_BUSINESS_ACCOUNT_SUCCESS';
export const CREATE_GOOGLE_BUSINESS_ACCOUNT_LOADING = 'CREATE_GOOGLE_BUSINESS_ACCOUNT_LOADING';
export const CREATE_GOOGLE_BUSINESS_ACCOUNT_ERROR = 'CREATE_GOOGLE_BUSINESS_ACCOUNT_ERROR';

export const CREATE_FACEBOOK_BUSINESS_ACCOUNT_SUCCESS = 'CREATE_FACEBOOK_BUSINESS_ACCOUNT_SUCCESS';
export const CREATE_FACEBOOK_BUSINESS_ACCOUNT_LOADING = 'CREATE_FACEBOOK_BUSINESS_ACCOUNT_LOADING';
export const CREATE_FACEBOOK_BUSINESS_ACCOUNT_ERROR = 'CREATE_FACEBOOK_BUSINESS_ACCOUNT_ERROR';

export const RESET_MANAGED_ACCOUNT_STATE = 'RESET_MANAGED_ACCOUNT_STATE';

export const GET_CREDITS = 'GET_CREDITS';
export const UPDATE_CREDITS = 'UPDATE_CREDITS';
export const CREATE_CREDITS = 'CREATE_CREDITS';
export const GET_CLIENT_ID_FOR_CREDITS = 'GET_CLIENT_ID_FOR_CREDITS';
export const CREDIT_ERROR = 'CREDIT_ERROR';
export const CLEAR_CREDITS_PURCHASE = 'CLEAR_CREDITS_PURCHASE';
export const CLEAR_CREDIT_ERRORS = 'CLEAR_CREDIT_ERRORS';

// Payment Actions
export const GET_PAYMENTS = 'GET_PAYMENTS';
export const UPDATE_PAYMENTS = 'UPDATE_PAYMENTS';
export const CREATE_PAYMENTS = 'CREATE_PAYMENTS';
export const GET_CLIENT_ID_FOR_PAYMENTS = 'GET_CLIENT_ID_FOR_PAYMENTS';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';
export const CLEAR_PAYMENTS_PURCHASE = 'CLEAR_PAYMENTS_PURCHASE';
export const CLEAR_PAYMENT_ERRORS = 'CLEAR_PAYMENT_ERRORS';

// Subscriptions Actions
export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const UPDATE_SUBSCRIPTIONS = 'UPDATE_SUBSCRIPTIONS';
export const CREATE_SUBSCRIPTIONS = 'CREATE_SUBSCRIPTIONS';
export const GET_CLIENT_ID_FOR_SUBSCRIPTIONS = 'GET_CLIENT_ID_FOR_SUBSCRIPTIONS';
export const SUBSCRIPTION_ERROR = 'SUBSCRIPTION_ERROR';
export const CLEAR_SUBSCRIPTIONS_PURCHASE = 'CLEAR_SUBSCRIPTIONS_PURCHASE';
export const CLEAR_SUBSCRIPTION_ERRORS = 'CLEAR_SUBSCRIPTION_ERRORS';

// Cards Actions
export const GET_CARDS = 'GET_CARDS';
export const UPDATE_CARDS = 'UPDATE_CARDS';
export const CREATE_CARDS = 'CREATE_CARDS';
export const GET_CLIENT_ID_FOR_CARDS = 'GET_CLIENT_ID_FOR_CARDS';
export const CARD_ERROR = 'CARD_ERROR';
export const CLEAR_CARDS_PURCHASE = 'CLEAR_CARDS_PURCHASE';
export const CLEAR_CARD_ERRORS = 'CLEAR_CARD_ERRORS';

export const STEP_COMPLETED = 'STEP_COMPLETED';
export const SELECT_CAMPAIGN_STEP = 'SELECT_CAMPAIGN_STEP';
export const CREATE_CAMPAIGN_STEP = 'CREATE_CAMPAIGN_STEP';
export const CONNECT_SOCIAL_STEP = 'CONNECT_SOCIAL_STEP';
export const TARGET_AUDIENCE_STEP = 'TARGET_AUDIENCE_STEP';
export const REVIEW_TARGETING_STEP = 'REVIEW_TARGETING_STEP';
export const BUDGET_STEP = 'BUDGET_STEP';
export const OBJECTIVE_STEP = 'OBJECTIVE_STEP';
export const PURCHASE_CREDITS_STEP = 'PURCHASE_CREDITS_STEP';
export const POST_AD_STEP = 'POST_AD_STEP';
export const STEP_ERROR = 'STEP_ERROR';
export const STEP_UNSET = 'STEP_UNSET';
